# Generated by Django 3.1.5 on 2021-06-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
