# Generated by Django 3.1.5 on 2021-05-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210506_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='hospDist',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='internet',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='marketDist',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='moskDist',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='parkDist',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='sanitation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='schoolDist',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='transitDist',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='uniDist',
            field=models.FloatField(),
        ),
    ]
