# Generated by Django 3.1.5 on 2021-05-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210506_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='internet',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='sanitation',
        ),
    ]
