# Generated by Django 3.1.5 on 2021-05-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210506_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='size',
            field=models.FloatField(),
        ),
    ]
