# Generated by Django 3.1.5 on 2021-06-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210506_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(max_length=100)),
                ('moskDist', models.FloatField()),
                ('parkDist', models.FloatField()),
                ('hospDist', models.FloatField()),
                ('marketDist', models.FloatField()),
                ('transitDist', models.FloatField()),
                ('schoolDist', models.FloatField()),
                ('uniDist', models.FloatField()),
            ],
        ),
    ]
