# Generated by Django 3.1.5 on 2021-06-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
